"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[░▒▓](matugen-color3)[󰣇](fg:matugen-color10 bg:matugen-color3)$username[](bg:matugen-color1 fg:matugen-color3)$directory[](fg:matugen-color1 bg:matugen-color11)$git_branch$git_status[](fg:matugen-color11 bg:matugen-color11)$nodejs$rust$golang$php[](fg:matugen-color11 bg:matugen-color7)$conda[ ](fg:matugen-color7)$line_break$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
matugen-color1 = '{{colors.primary_fixed_dim.default.hex}}'
matugen-color2 = '{{colors.on_primary.default.hex}}'
matugen-color3 = '{{colors.on_surface_variant.default.hex}}'
matugen-color4 = '{{colors.surface_container.default.hex}}'
matugen-color5 = '{{colors.on_primary.default.hex}}'
matugen-color6 = '{{colors.on_primary.default.hex}}'
matugen-color7 = '{{colors.surface.default.hex}}'
matugen-color8 = '{{colors.primary.default.hex}}'
matugen-color9 = '{{colors.tertiary.default.hex}}'
matugen-color10 = '{{colors.on_primary_fixed.default.hex}}'
matugen-color11 = '{{colors.primary_container.default.hex}}'
matugen-color12 = '{{colors.on_secondary.default.hex}}'
color0 = 'black'
color1 = 'red'
color2 = 'green'
color3 = 'yellow'
color4 = 'blue'
color5 = 'magenta'
color6 = 'cyan'
color7 = 'white'
color8 = '#8bd5b5'
color9 = '#a6cce0'
color10 = '#002115'
color11 = '#00513a'
color12 = '#1f352b'

[username]
show_always = true
style_user = "fg:matugen-color10 bg:matugen-color3"
style_root = "fg:matugen-color10 bg:matugen-color3"
format = "[ $user ]($style)"
disabled = false

[directory]
style = "fg:matugen-color7 bg:matugen-color1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:matugen-color11"
format = '[ $symbol $branch ](fg:matugen-color7 bg:matugen-color11)'

[git_status]
style = "bg:matugen-color11"
format = '[($all_status$ahead_behind )](fg:matugen-color7 bg:matugen-color11)'

[nodejs]
symbol = ""
style = "bg:matugen-color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:matugen-color11)]($style)'

[rust]
symbol = ""
style = "bg:matugen-color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:matugen-color11)]($style)'

[golang]
symbol = ""
style = "bg:matugen-color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:matugen-color11)]($style)'

[php]
symbol = ""
style = "bg:matugen-color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:matugen-color11)]($style)'

[conda]
symbol = " "
style = "bg:matugen-color12"
format = '[ $symbol$environment ](fg:matugen-color3 bg:matugen-color12)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:matugen-color12"
format = '[[  $time ](fg:matugen-color3 bg:matugen-color12)]($style)'
