background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(87d1ea)
    inner_color = rgb(0f1416)
    font_color = rgb(dee3e6)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}
