cursor #eddfe4
cursor_text_color #d3c2ca

foreground            #eddfe4
# background            #141414
selection_foreground  #3f2a37
selection_background  #ddbecf
url_color             #f8b1dd

# black
# color8   #585252
# color0   #4c4c4c

# red
color1   #b8545b
color9   #b15b5f

# green
color2   #f8b1dd
color10  #f8b1dd

# yellowwa
color3   #b1aa63
color11  #beb769

# blue
/* color4  #776dafff */
color4  #f8b1dd
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
